---
LOGLEVEL: DEBUG
LOGFILE: mtec2mqtt.log

# Add your data here:
PV_EMAIL : ""               # e-mail address you used to register at M-TEC portal
PV_PASSWORD : ""            # password you used to register at M-TEC portal
PV_DEVICE_ID: ""            # ID of the device the data should be fetched from. Can be determined using MTEC_client.py
PV_DEVICE_MQTT_ALIAS: ""    # Name of the device to be used in the MQTT topic. If left empty, the device ID will be used.

MQTT_BROKER: ""             # Hostname of the mqtt-broker
MQTT_PORT: ""               # Port of the mqtt-broker, defaults to 1883 if left empty
MQTT_BASE_TOPIC: ""         # base-topic, which should be used to post messages to mqtt
MQTT_USER: ""               # Username to authenticate to the mqtt-broker (optional)
MQTT_PASSWORD: ""           # Password to authenticate to the mqtt-broker (optional)
MQTT_INTERVAL: "60"         # Interval (in seconds) used to query api and post values to Broker (in seconds)

##########################
# Base config - probably no need to change
PV_BASE_URL : "https://energybutler.mtec-portal.com/api/sys/"  # Base URL of API
PV_TIMEOUT : 3         # Timeout (seconds) for querying the API
PV_MAX_LOGIN_RETRY : 3 # No. of retries for login

PV_DEMO_ACCOUNT : "2312942037@qq.com"    # e-mail adress of Demo account
PV_DEMO_STATION_ID : "1587705243920052226"

